name: android_printer_service
description: "A Flutter plugin to print documents on Android devices via native print service."
version: 0.0.2
homepage: https://github.com/duypxd/android_print_service
publish_to: "https://pub.dev"

environment:
  sdk: ^3.9.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.android_printer_service
        pluginClass: ForwardPrintPlugin
